services:
  storage:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rahasia
      - POSTGRES_DB=pubsub_db
    #ports:
    # - "5432:5432" # Diekspos agar bisa dicek via DBeaver nanti
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d # Menjalankan file SQL otomatis saat pertama kali up

  aggregator:
    build: ./aggregator
    image: pubsub-aggregator:latest
    depends_on:
      - storage
    environment:
      - DATABASE_URL=postgresql://admin:rahasia@storage:5432/pubsub_db
    ports:
      - "8080:8080"

  publisher:
    build: ./publisher
    image: pubsub-publisher:latest
    depends_on:
      - aggregator
    environment:
      - TARGET_URL=http://aggregator:8080/publish

volumes:
  pg_data:
    # Named volume ini yang akan menyelamatkan datamu (persisten) walau container dihapus